jQuery(function(){var b=jQuery("#ctxps-grouplist-ddl");b.data("options",b.html()).children(".detach").remove();jQuery("#ctxps-grouplist-ddl").data("options",jQuery("#ctxps-grouplist-ddl").html()).children(".detach").remove();jQuery("#ctxps-grouplist-box #ctxps-cb-protect").click(function(){CTXPS_Ajax.toggleContentSecurity("post",parseInt(jQuery("#ctx_ps_post_id").val()),"#ctxps-grouplist-box h3.hndle")});jQuery('#ctxps-grouplist-box label[for="ctx_ps_protectmy"]').click(function(){jQuery("#ctx_ps_protectmy:disabled").length>
0&&alert(ctxpsmsg.NoUnprotect)});jQuery("#add_group_page").click(function(){CTXPS_Ajax.addGroupToPage()});jQuery("#edittag #ctxps-cb-protect").click(function(){CTXPS_Ajax.toggleContentSecurity("term",parseInt(jQuery('#edittag input[name="tag_ID"]').val()))});jQuery('#edittag label[for="ctxps-cb-protect"]').click(function(){jQuery("#ctxps-cb-protect:disabled").length>0&&alert(ctxpsmsg.NoUnprotect)});jQuery("#ctxps-grouplist-ddl-btn").click(function(){CTXPS_Ajax.addGroupToTerm()});jQuery("#btn-add-grp-2-user").click(function(){CTXPS_Ajax.addGroupToUser()});
jQuery("#enrollit").click(function(){CTXPS_Ajax.addBulkUsersToGroup()});jQuery("#ad-protect-site:checked").click(function(){return jQuery(this).filter(":checked").length===0?confirm(ctxpsmsg.SiteProtectDel):!0});jQuery('#ad-msg-enable, label[for="ad-msg-enable"]').click(function(){var b=jQuery(".toggle-opts-ad-msg"),a=jQuery(".toggle-opts-ad-page"),c=jQuery("#ad-msg-forcelogin:checked").length;jQuery(this).filter(":checked").length?c?b.not(".ad-opt-anon").fadeOut(250,function(){a.not(".ad-opt-anon").fadeIn(250)}):
b.fadeOut(250,function(){jQuery(".toggle-opts-ad-page").fadeIn(250)}):c?a.not(".ad-opt-anon").fadeOut(250,function(){b.not(".ad-opt-anon").fadeIn(250)}):a.fadeOut(250,function(){b.fadeIn(250)})});jQuery('#ad-msg-forcelogin, label[for="ad-msg-forcelogin"]').click(function(){var b=jQuery(".ad-opt-anon"),a=jQuery("#ad-msg-enable:checked").length;jQuery(this).filter(":checked").length?b.filter(":visible").fadeOut(250):a?jQuery(".toggle-opts-ad-page").fadeIn(250):jQuery(".toggle-opts-ad-msg").fadeIn(250)})});
function CTXPS_Ajax(){}CTXPS_Ajax.addBulkUsersToGroup=function(){var b=jQuery("#the-list input:checkbox:checked");jQuery.get("admin-ajax.php",{action:"ctxps_user_bulk_add",users:b.serializeArray(),group_id:jQuery("#psc_group_add").val()},function(d){var d=jQuery(d),a=jQuery("#message"),c=d.find("supplemental html").text();a.length?a.replaceWith(c):jQuery("#wpbody-content h2:first").after(c);d.find("bulk_enroll").attr("id")=="1"&&b.removeAttr("checked").prop("checked",!1)},"xml")};
CTXPS_Ajax.showSaveMsg=function(b){jQuery(b+" .ctx-ajax-status").length==0&&jQuery(b).append('<span class="ctx-ajax-status">Saved</span>').find(".ctx-ajax-status").fadeIn(500,function(){jQuery(this).delay(750).fadeOut(500,function(){jQuery(this).remove()})})};
CTXPS_Ajax.toggleSecurity=function(){var b=parseInt(jQuery("#ctx_ps_post_id").val());jQuery("#ctx_ps_protectmy:checked").length!==0?jQuery.get("admin-ajax.php",{action:"ctxps_security_update",setting:"on",object_type:"post",object_id:b},function(b){b=jQuery(b);b.find("update_sec").attr("id")=="1"?(jQuery("#ctx_ps_pagegroupoptions").show(),CTXPS_Ajax.showSaveMsg("#ctxps-grouplist-box h3.hndle")):alert(ctxpsmsg.GeneralError+b.find("wp_error").text())},"xml"):confirm(ctxpsmsg.EraseSec)?jQuery.get("admin-ajax.php",
{action:"ctxps_security_update",setting:"off",object_type:"post",object_id:b},function(b){b=jQuery(b);b.find("update_sec").attr("id")=="1"?(jQuery("#ctx_ps_pagegroupoptions").hide(),CTXPS_Ajax.showSaveMsg("#ctxps-grouplist-box h3.hndle")):alert(ctxpsmsg.GeneralError+b.find("wp_error").text())},"xml"):jQuery("#ctx_ps_protectmy").attr("checked","checked").prop("checked","checked")};
CTXPS_Ajax.toggleContentSecurity=function(b,d,a){jQuery("#ctxps-grouplist-ddl");typeof b=="undefined"&&alert("Programming Error: Type was undefined. Changes not saved.");typeof d=="undefined"&&(d=parseInt(jQuery("#ctxps-object-id").val()));jQuery("#ctxps-cb-protect:checked").length!==0?jQuery.get("admin-ajax.php",{action:"ctxps_security_update",setting:"on",object_type:b,object_id:d},function(c){c=jQuery(c);if(c.find("update_sec").attr("id")=="1"){if(c.find("supplemental html").length!=0)switch(b){case "term":jQuery("#the-list-ctxps-relationships").replaceWith(c.find("supplemental html").text())}jQuery("#ctxps-relationships-list").show();
typeof a!="undefined"&&CTXPS_Ajax.showSaveMsg(a)}else alert(ctxpsmsg.GeneralError+c.find("wp_error").text())},"xml"):confirm(ctxpsmsg.EraseSec)?jQuery.get("admin-ajax.php",{action:"ctxps_security_update",setting:"off",object_type:b,object_id:d},function(c){c=jQuery(c);if(c.find("update_sec").attr("id")=="1"){jQuery("#ctxps-relationships-list").hide();if(c.find("supplemental html").length>0)switch(b){case "term":jQuery("#the-list-ctxps-relationships").replaceWith(c.find("supplemental html").text())}typeof save_loc!=
"undefined"&&CTXPS_Ajax.showSaveMsg(a);jQuery("#ctxps-grouplist-box #ctx-parentmsg").length>0&&jQuery("#publish").click()}else alert(ctxpsmsg.GeneralError+c.find("wp_error").text())},"xml"):jQuery("#ctxps-cb-protect").attr("checked","checked").prop("checked","checked")};
CTXPS_Ajax.addGroupToUser=function(){var b=parseInt(jQuery("#ctxps-grouplist-ddl").val()),d=parseInt(jQuery("#ctx-group-user-id").val());b!=0?(jQuery("#btn-add-grp-2-user").attr("disabled","disabled").prop("disabled","disabled"),jQuery.get("admin-ajax.php",{action:"ctxps_add_group_to_user",group_id:b,user_id:d},function(a){a=jQuery(a);a.find("enroll").attr("id")=="1"?(jQuery("#grouptable > tbody").html(a.find("supplemental html").text()),a=jQuery("#ctxps-grouplist-ddl"),a.html(a.data("options")).children('option[value="'+
b+'"]').addClass("detach").end().data("options",a.html()).children(".detach").remove(),jQuery("#btn-add-grp-2-user").removeAttr("disabled").prop("disabled",!1),CTXPS_Ajax.showSaveMsg(".ctx-ps-tablenav")):alert(ctxpsmsg.GeneralError+data.find("wp_error").text())},"xml")):alert(ctxpsmsg.NoGroupSel)};
CTXPS_Ajax.removeGroupFromUser=function(b,d,a){jQuery.get("admin-ajax.php",{action:"ctxps_remove_group_from_user",groupid:b,user_id:d},function(c){c=jQuery(c);if(c.find("unenroll").attr("id")=="1"){var d=jQuery("#ctxps-grouplist-ddl");d.html(d.data("options")).children('option[value="'+b+'"]').removeClass("detach").end().data("options",d.html()).children(".detach").remove();a.parents("tr:first").fadeOut(500,function(){a.parents("tbody:first").html(c.find("supplemental html").text())});CTXPS_Ajax.showSaveMsg(".ctx-ps-tablenav")}else alert(ctxpsmsg.GeneralError+
data.find("wp_error").text())},"xml")};
CTXPS_Ajax.addGroupToPage=function(){var b=parseInt(jQuery("#ctxps-grouplist-ddl").val()),d=parseInt(jQuery("#ctx_ps_post_id").val());b!=0?jQuery.get("admin-ajax.php",{action:"ctxps_add_group_to_post",group_id:b,post_id:d},function(a){a=jQuery(a);a.find("add_group").attr("id")=="1"&&(jQuery("#ctx-ps-page-group-list").html(a.find("supplemental html").text()),a=jQuery("#ctxps-grouplist-ddl"),a.html(a.data("options")).children('option[value="'+b+'"]').addClass("detach").end().data("options",a.html()).children(".detach").remove(),
CTXPS_Ajax.showSaveMsg("#ctxps-grouplist-box h3.hndle"))},"xml"):alert(ctxpsmsg.NoGroupSel)};
CTXPS_Ajax.addGroupToTerm=function(){var b=jQuery("#ctxps-grouplist-ddl").val(),d=jQuery('#edittag input[name="tag_ID"]').val(),a=jQuery('#edittag input[name="taxonomy"]').val();typeof b!="undefined"&&b!=0?jQuery.get("admin-ajax.php",{action:"ctxps_add_group_to_term",group_id:b,content_id:d,taxonomy:a},function(c){c=jQuery(c);c.find("add_group").attr("id")=="1"&&(jQuery("#the-list-ctxps-relationships").replaceWith(c.find("supplemental html").text()),c=jQuery("#ctxps-grouplist-ddl"),c.html(c.data("options")).children('option[value="'+
b+'"]').addClass("detach").end().data("options",c.html()).children(".detach").remove(),typeof savemsg_selector!="undefined"&&CTXPS_Ajax.showSaveMsg(savemsg_selector))},"xml"):alert(ctxpsmsg.NoGroupSel)};
CTXPS_Ajax.addGroupToContent=function(b,d,a,c,e,f){typeof b!="undefined"&&b!=0?jQuery.get("admin-ajax.php",{action:"ctxps_add_group_to_term",group_id:b,content_type:d,content_id:a},function(a){a=jQuery(a);a.find("add_group").attr("id")=="1"&&(typeof c!="undefined"&&jQuery(c).html(a.find("supplemental html").text()),a=jQuery(e),a.html(a.data("options")).children('option[value="'+b+'"]').addClass("detach").end().data("options",a.html()).children(".detach").remove(),typeof f!="undefined"&&CTXPS_Ajax.showSaveMsg(f))},
"xml"):alert(ctxpsmsg.NoGroupSel)};
CTXPS_Ajax.removeGroupFromPage=function(b,d){if(confirm(ctxpsmsg.RemoveGroup.replace(/%s/,d.parents(".ctx-ps-sidebar-group:first").children(".ctx-ps-sidebar-group-title").text()))){var a=parseInt(jQuery("#ctx_ps_post_id").val());jQuery.get("admin-ajax.php",{action:"ctxps_remove_group_from_page",group_id:b,post_id:a,requester:"sidebar"},function(a){a=jQuery(a);if(a.find("remove_group").attr("id")=="1"){var e=jQuery("#ctxps-grouplist-ddl");e.html(e.data("options")).children('option[value="'+b+'"]').removeClass("detach").end().data("options",
e.html()).children(".detach").remove();d.parent().fadeOut(500,function(){console.log("Removed");jQuery("#ctx-ps-page-group-list").html(a.find("supplemental html").text())});CTXPS_Ajax.showSaveMsg("#ctxps-grouplist-box h3.hndle")}else alert(ctxpsmsg.GeneralError+a.find("wp_error").text())},"xml")}};
CTXPS_Ajax.removeGroupFromTerm=function(b,d){var a=jQuery('#edittag input[name="tag_ID"]').val(),c=jQuery('#edittag input[name="taxonomy"]').val(),e=jQuery("#the-list-ctxps-relationships");confirm(ctxpsmsg.RemoveGroup.replace(/%s/,d.parents("tr:first").children("td.column-name a:first").text()))&&jQuery.get("admin-ajax.php",{action:"ctxps_remove_group_from_term",group_id:b,content_id:a,taxonomy:c},function(a){a=jQuery(a);if(a.find("remove_group").attr("id")=="1"){var c=jQuery("#ctxps-grouplist-ddl");
c.html(c.data("options")).children('option[value="'+b+'"]').removeClass("detach").end().data("options",c.html()).children(".detach").remove();d.parents("tr:first").fadeOut(500,function(){e.replaceWith(a.find("supplemental html").text())})}else alert(ctxpsmsg.GeneralError+a.find("wp_error").text())},"xml")};
CTXPS_Ajax.removePageFromGroup=function(b,d){if(confirm(ctxpsmsg.RemovePage.replace(/%s/,d.parents("td:first").find("strong>a:first").text()))){var a=parseInt(jQuery("#groupid").val());jQuery.get("admin-ajax.php",{action:"ctxps_remove_group_from_page",group_id:a,post_id:b},function(a){a=jQuery(a);a.find("remove_group").attr("id")=="1"?d.parents("tr:first").fadeOut(500,function(){jQuery(this).parents("tbody:first").html(a.find("supplemental html").text())}):alert(ctxpsmsg.GeneralError+a.find("wp_error").text())},
"xml")}};